name: Run MATLAB Tests on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: sccn/eeglab
          path: lib/eeglab_git
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run Tests (for now manually)
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('lib/eeglab_git');init_unfold;plugin_askinstall('clean_rawdata','clean_data',1);addpath('unittests');run('uf_tests.m')
